### ISSUE TITLE
Login broken for users without assigned ticker

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/ticker-admin#15]
If you login with a user who doesn't have any ticker assigned, the ticker admin behaves weird. For a short moment, you see some rendered page, but it immediately disappears and then only a white page is displayed.

Would be better to get a warning along the lines of "you don't have a ticker assigned, please ask the admins".

**Comment by kjoscha** [comment]
I just got the same issie. Problem is due to ticker mapping in TickerList.js, where `tickers.map(ticker => {`  crashes with tickers being null
