### ISSUE TITLE
Selected ticker permissions get lost when adding new users

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/ticker-admin#16]
When adding a new user, the selected ticker permissions get lost.

If you later go back to the users settings, select ticker permissions and save the settings, it works as expected. But when creating a new user, the selected ticker permissions are not stored.

**Comment by 0x46616c6b** [comment]
Fixed in Ticker API https://github.com/systemli/ticker/commit/354908780fe4f1ff2951f8b3071fecc6750d842f
