### ISSUE TITLE
Save geolocation

### ISSUE THREAD

**Issue by kjoscha** [systemli/ticker-admin#18]
We want to introduce the possibility of saving geolocation related to ticker events. Therefore, we need attributes served by the backend, either

- latitude + longitude if only punctual locations

or

- json if complex features like areas, lines or multiple points

 are desired. What do you think?

**Comment by 0x46616c6b** [comment]
For the first iteration I would suggest adding property `location` with followings structure

```
"location": {
  "latitude": 0,
  "longitude": 0
}
```

So we are able to extend it later with areas and POI. What do you think?

**Comment by kjoscha** [comment]
We could use a more generic format based on the geojson definition. In the end, it has to be geojson to use it in a js map library (i.e. leaflet) anyway.

This is an example for a geojson feature collection:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          16.5234375,
          48.922499263758255
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              48.515625,
              43.068887774169625
            ],
            [
              88.9453125,
              43.068887774169625
            ],
            [
              88.9453125,
              59.712097173322924
            ],
            [
              48.515625,
              59.712097173322924
            ],
            [
              48.515625,
              43.068887774169625
            ]
          ]
        ]
      }
    }
  ]
}
```

We could save only the geometry part:

```
"geometry": {
  "type": "Point",
  "coordinates": [0, 0]
 } 
```
or
```
"geometry": {
  "type": "Polygon",
  "coordinates": [[0, 0],[1,1][1,2]]
 } 
```
...

**Comment by 0x46616c6b** [comment]
Like your idea. A quick search shows that there is a implementation in Go, so we can use the full GeoJSON Features: https://github.com/paulmach/go.geojson

**Comment by kjoscha** [comment]
Ok, cool. So, as we start to work on the interface implementation, we expect to have an endpoint dealing with full geojson feature collections? Then, it will also be possbile to save multiple geometries with one ticker event which could be useful. In addition, this is the easiest way to deliver data from the leaflet editor.

**Comment by 0x46616c6b** [comment]
I would extend the POST Api for messages and the struct for the json response. What do you think, should we support from the beginning multiple Geometry? I don't have a special feeling about that.

**Comment by kjoscha** [comment]
> What do you think, should we support from the beginning multiple Geometry?

Yes, i would suggest to do so, since it should not bring any extra effort. Does it? The location function can be much more versatile that way - from experience speaking :)

**Comment by 0x46616c6b** [comment]
Then I would follow your suggestion. Do you want to implement it in the ticker and ticker-admin or should I take one part?

**Comment by InnoZ** [comment]
We are currently implementing ticker-admin. It will be ready for review soon. How should we post the geojson? Together with the message input as following?

```
export function postMessage(ticker, text, geojson) {
    return Auth.fetch(`${ApiUrl}/admin/tickers/${ticker}/messages`, {
        body: JSON.stringify({
            text: text,
            geojson: geojson
        }),
        method: 'POST'
    });
}
```

**Comment by kjoscha** [comment]
We are currently implementing ticker-admin. It will be ready for review soon. How should we post the geojson? Together with the message input as following?

```
export function postMessage(ticker, text, geojson) {
    return Auth.fetch(`${ApiUrl}/admin/tickers/${ticker}/messages`, {
        body: JSON.stringify({
            text: text,
            geojson: geojson
        }),
        method: 'POST'
    });
}
```

**Comment by 0x46616c6b** [comment]
I would rename it to `location`.

**Comment by kjoscha** [comment]
We just discussed that. In our opinion location only describes a single point. Since it will be possible to save multiple geo features as points, lines and polygons with one message, a more generic name would be helpful. We would choose "geo_information"

![Bildschirmfoto vom 2019-06-12 15-42-57](https://user-images.githubusercontent.com/3657707/59356251-ca139500-8d28-11e9-8f62-2c6adb3cc8a9.png)

**Comment by pr0totyp** [comment]
The form field in screenshot will be hidden. The geo_json object should already be valid and only be checked in the backend after submitting.

**Comment by 0x46616c6b** [comment]
ACK

**Comment by 0x46616c6b** [comment]
I will start implementation in ticker-api as soon as possible.

**Comment by 0x46616c6b** [comment]
Its already implemented.

**Comment by kjoscha** [comment]
Hey :wave: @pr0totyp and me are ready for new feature contributions. Just tag us in any issue
